apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  storageClassDevices:
    - storageClassName: "local-sc" 
      forceWipeDevicesAndDestroyAllData: false 
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/md126
        - /dev/md127

